### ISSUE TITLE
How to set "target" in message from client to server

### ISSUE THREAD

**Issue by davedawkins** [Shmew/Fable.SignalR#22]
Hi, first, thanks for this library, great work and documentation.

How do I set the `target` of a message? I've been through the source code, and got myself a little lost.

Following the docs, I can get a message like the one on the right in the screenshot below, but my server is expecting a message in the format on the left. We'll be changing the protocol once we have a PoC working, this is a learning phase. Thank you!

![image](https://user-images.githubusercontent.com/285421/112185623-4e7e9180-8bf8-11eb-9272-d7828f865b96.png)

I'm using Elmish, but can drop back to native if it gives me access to a richer/more flexible API.

Thanks

**Comment by Shmew** [comment]
Hi @davedawkins,

It sounds like you're using `Fable.SignalR.Elmish` against a server that isn't running `Fable.SignalR.AspNetCore`/`Fable.SignalR.Saturn`, is that right? 

The main goal I had when writing the library was to get rid of the magic string usage and improve type safety. The downside of this is that it requires both the client and server to be running their respective packages. This is because I override the default protocol implementations, construct the `Microsoft.AspNetCore.SignalR.Hub` with a very specific structure, and require the DU defining the shape of messages to be shared between the server and client. 

You can see [here](https://github.com/Shmew/Fable.SignalR/blob/master/src/Fable.SignalR.AspNetCore/Server.fs#L53-L78) that the hubs are always created with a `Send` and `Invoke` method, which the targets are set based on the type of call made from the client. 

If you're able to use the previously mentioned server libraries it's an easy fix, but if that's not possible this likely won't be able to work well for you. You'd have to write your own `IHubProtocol` implementation to convert the message you're receiving into one that's usable from your own hubs as well as handle the "Invoke" target.

**Comment by davedawkins** [comment]
Hi @Shmew 
Well, we're running a C# Kestrel ASP.NET server, with a wonky (test) API.  It's one half of a Blazor app.

I can see now that Fable.SignalR intends to run against itself on the server.  I totally understand where you're coming from with that, and it's a beautiful solution when you can run F# on both client and server.

It's possible that we could switch our server to F# and then adopt `Fable.SignalR`. It almost looks then as if we can switch our C# server API to adopt `Send` and `Invoke` targets, whereupon we might be able to proceed. Is it as straightforward as that? You mention overriding default protocol implementations. This sounds like a new protocol that sits on SignalR.

I note that you do say that this likely won't work. I'd then be looking at creating a Fable wrapper for SignalR that was a direct projection of those APIs, but I really don't want to do that. For a start, that's a lot of work, and secondly, I'd want to release it as a package and that would create some confusion. I guess I could easily avoid the second part by keeping it in house.

I appreciate the help; if you have any thoughts on what we can do to the server to make it talk Fable.SignalR using AspNetSignalR that would be great, or how to tunnel down below the DU-based protocol.

**Comment by Shmew** [comment]
In that scenario (if switching to F# on the server isn't ideal), I think the easiest solution is to use the normal shared `fsproj` with the DU type and then just use the `Fable.SignalR.AspNetCore` library from your C# server. It already has a [fluent config builder](https://shmew.github.io/Fable.SignalR/#/signalr-server/api#signalrconfigbuilder) and has targets for both .NET 3.1 and 5.0. The only part that will be a little rough is handling the DU from C#. You could write a function to convert it to something more easily handled in C# and import it. Even better would be if an F# proj could import the code for your hubs and then expose the functions for your web app to pass into the library. Your hubs would then just need to be changed to not inherit `Hub` and a slight adjustment on the function signatures, but I don't think it would be too bad.

**Comment by davedawkins** [comment]
Brilliant ideas. It's almost as if F# and C# are supposed to be able to work together!

Thanks for the input.
