### ISSUE TITLE
Detecting initial connection (client side)

### ISSUE THREAD

**Issue by davedawkins** [Shmew/Fable.SignalR#25]
Message `RegisterHub` lets me access `hub.hub.state` to find the initial connection status (so far that's been "Connecting"), and the connection builder lets me register `OnReconnecting` and `OnReconnected` handlers. What's the right way for me to detect initial the initial connection?

https://shmew.github.io/Fable.SignalR/#/signalr-client/api#hubconnectionbuilder

Thank you!

**Comment by davedawkins** [comment]
Checking the MS SignalR docs I can see that this isn't really a `Fable.SignalR` issue, it's a general SignalR question. Feel free to close this, I'll poke around the main SignalR docs.

**Comment by Shmew** [comment]
There's a few different approaches you can take, generally I just throw a promise so that when the connection is established (via `hub.Start()`) and I load the initial data I need that the page stops displaying a loader. You could also try doing something with a custom [retry policy](https://shmew.github.io/Fable.SignalR/#/signalr-client/api#retrypolicy).
